version: "3"

services:
  server:
    container_name: gaethering-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ".env"
    restart: always
    depends_on:
      - database
      - redis
      - rabbitmq

  database:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - ".env"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - /var/lib/mysql

  redis:
    image: redis
    container_name: redis
    command: redis-server
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - ".env"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-stream
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    volumes:
      - ".docker/rabbitmq/data/log:/data/log"
      - ".docker/rabbitmq/data/mnesia:/data/mnesia"
      - ".docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    restart: always
    env_file:
      - ".env"